package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Long cartId;
     private String email;
     private long PId;
     private long quantity;
     private long cprice;
     private long total;

    public Cart() {
    }

    public Cart(String email, long PId, long quantity, long cprice, long total) {
       this.email = email;
       this.PId = PId;
       this.quantity = quantity;
       this.cprice = cprice;
       this.total = total;
    }
   
    public Long getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public long getPId() {
        return this.PId;
    }
    
    public void setPId(long PId) {
        this.PId = PId;
    }
    public long getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }
    public long getCprice() {
        return this.cprice;
    }
    
    public void setCprice(long cprice) {
        this.cprice = cprice;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


