package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Long categoryId;
     private String categoryTitle;
     private String categoryDescription;

    public Category() {
    }

    public Category(String categoryTitle, String categoryDescription) {
       this.categoryTitle = categoryTitle;
       this.categoryDescription = categoryDescription;
    }
   
    public Long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryTitle() {
        return this.categoryTitle;
    }
    
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }
    public String getCategoryDescription() {
        return this.categoryDescription;
    }
    
    public void setCategoryDescription(String categoryDescription) {
        this.categoryDescription = categoryDescription;
    }




}


