package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeliveryBoyDetails generated by hbm2java
 */
public class DeliveryBoyDetails  implements java.io.Serializable {


     private long dbTransId;
     private long dbId;
     private long orderId;
     private Date picDate;

    public DeliveryBoyDetails() {
    }

    public DeliveryBoyDetails(long dbTransId, long dbId, long orderId, Date picDate) {
       this.dbTransId = dbTransId;
       this.dbId = dbId;
       this.orderId = orderId;
       this.picDate = picDate;
    }
   
    public long getDbTransId() {
        return this.dbTransId;
    }
    
    public void setDbTransId(long dbTransId) {
        this.dbTransId = dbTransId;
    }
    public long getDbId() {
        return this.dbId;
    }
    
    public void setDbId(long dbId) {
        this.dbId = dbId;
    }
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }
    public Date getPicDate() {
        return this.picDate;
    }
    
    public void setPicDate(Date picDate) {
        this.picDate = picDate;
    }




}


