package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Long orderId;
     private Date orderDate;
     private String orderDetails;
     private long pid;

    public Order() {
    }

    public Order(Date orderDate, String orderDetails, long pid) {
       this.orderDate = orderDate;
       this.orderDetails = orderDetails;
       this.pid = pid;
    }
   
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public String getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(String orderDetails) {
        this.orderDetails = orderDetails;
    }
    public long getPid() {
        return this.pid;
    }
    
    public void setPid(long pid) {
        this.pid = pid;
    }




}


