package Pojo;
// Generated 7 Mar, 2021 12:51:36 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long userId;
     private String userName;
     private String userEmail;
     private String userPassword;
     private String userPhone;
     private String userType;
     private String userAddress;

    public User() {
    }
    public User(String userEmail, String userPassword) {
       this.userEmail = userEmail;
       this.userPassword = userPassword;
    }
    public User(String userName, String userEmail, String userPassword, String userPhone, String userType, String userAddress) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.userPassword = userPassword;
       this.userPhone = userPhone;
       this.userType = userType;
       this.userAddress = userAddress;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }




}


